import re
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Notebook
from app.services.studio.generate import STUDIO_USER, generate_json, save_artifact, source_ids_from_args, topic_from_args

DEFAULT_TOPIC = "Leistungen, Angebote, Prozesse und Fakten"
AI_NOTICE = "This text was generated by AI. Check the sources."
_NUMBER = re.compile(r"-?\d+(?:[.,]\d+)?")

SKILL_GUIDE = """Infografik nur aus den gewählten Quellen.
items: vier bis acht Blöcke mit label, value und detail.
Optional auf einem Block: number, suffix, caption.
number: die hervorgehobene Zahl aus den Quellen.
suffix: beliebige Einheit oder Zeichen (%, €, Min., +).
caption: eine kurze Zeile unter der Zahl.
Setze number nur, wenn die Quellen diese Zahl nennen.
charts: nur wenn die Anweisung ein Diagramm verlangt und die Quellen vergleichbare Zahlen derselben Einheit nennen.
Erlaubte charts[].type: bar (Säulen), hbar (Balken), pie (Kreis).
Jedes Diagramm braucht title, unit, cite und mindestens zwei points mit label und value.
cite ist die Quellennummer wie [1].
Hänge Zitate [n] an caption oder detail, wenn ein Fakt aus einer Quelle stammt.
Keine erfundenen Zahlen. Ohne gültiges Diagramm: charts = [].
"""

SYSTEM = f"""Du bist Everlast Notebook, ein KI-System. Sage das klar.
Folge dieser Fähigkeitsbeschreibung:
{SKILL_GUIDE}
Erfinde keine Fakten.
Antworte nur mit einem JSON-Objekt.
Schema: {{"title": "string", "items": [{{"label": "string", "value": "string", "detail": "string", "number": "string", "suffix": "string", "caption": "string"}}], "charts": [{{"type": "string", "title": "string", "unit": "string", "cite": "string", "points": [{{"label": "string", "value": 0}}]}}]}}
"""


def _clean(value: Any) -> str:
    return " ".join(str(value or "").split())


def highlight_fields(entry: dict[str, Any]) -> tuple[str, str, str]:
    raw = entry.get("number")
    if isinstance(raw, bool):
        number = ""
    elif isinstance(raw, int) or isinstance(raw, float):
        number = f"{raw:g}"
    else:
        number = _clean(raw)[:24]
    suffix = _clean(entry.get("suffix"))[:24]
    caption = _clean(entry.get("caption"))
    return number, suffix, caption


def _is_junk(label: str, value: str, detail: str, number: str = "", caption: str = "") -> bool:
    if number:
        if not label:
            return True
        if not (value or detail or caption):
            return True
        if AI_NOTICE in f"{label} {value} {detail} {caption}" and len(detail + caption) < 80:
            return True
        return False
    if not label or not value:
        return True
    if AI_NOTICE in f"{label} {value} {detail}" and len(detail) < 80:
        return True
    compact = "".join(ch.lower() for ch in f"{label}{value}" if ch.isalnum())
    if len(set(compact)) < 4:
        return True
    if value.lower() == label.lower() and len(value) < 24:
        return True
    if detail.lower() == value.lower() and len(value) < 24:
        return True
    return False


def normalize_items(raw: Any) -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    if not isinstance(raw, list):
        return items
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        label = _clean(entry.get("label"))
        value = _clean(entry.get("value"))
        detail = _clean(entry.get("detail"))
        number, suffix, caption = highlight_fields(entry)
        if _is_junk(label, value, detail, number, caption):
            continue
        if number and not value:
            value = caption or detail[:80]
        key = (label.lower(), (value or number).lower())
        if key in seen:
            continue
        seen.add(key)
        item = {"label": label, "value": value, "detail": detail}
        if number:
            item["number"] = number
            item["suffix"] = suffix
            item["caption"] = caption
        items.append(item)
    return items


def items_from_citations(citations: list[Any]) -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    seen: set[str] = set()
    for cite in citations:
        if not isinstance(cite, dict):
            continue
        title = _clean(cite.get("source_title"))
        quote = _clean(cite.get("quote"))
        if not title or not quote:
            continue
        if title.lower() in seen:
            continue
        if AI_NOTICE in quote and len(quote) < 160:
            continue
        seen.add(title.lower())
        sentence = quote.split(".")[0].strip()
        value = sentence[:80] if sentence else title
        items.append({"label": title[:48], "value": value, "detail": quote[:220]})
    return items


def build_items(payload: dict[str, Any]) -> list[dict[str, str]]:
    items = normalize_items(payload.get("items"))
    if len(items) < 4:
        extra = items_from_citations(payload.get("citations") or [])
        items = normalize_items(items + extra)
    return items[:8]


def parse_number(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int) or isinstance(value, float):
        return float(value)
    match = _NUMBER.search(str(value or "").replace(",", "."))
    if match is None:
        return None
    return float(match.group(0))


def normalize_charts(raw: Any) -> list[dict[str, Any]]:
    charts: list[dict[str, Any]] = []
    if not isinstance(raw, list):
        return charts
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        kind = str(entry.get("type") or "").lower()
        if kind not in {"bar", "hbar", "pie"}:
            continue
        points: list[dict[str, Any]] = []
        for point in entry.get("points") or []:
            if not isinstance(point, dict):
                continue
            label = _clean(point.get("label"))
            number = parse_number(point.get("value"))
            if not label or number is None or number < 0:
                continue
            points.append({"label": label, "value": number})
        if len(points) < 2:
            continue
        charts.append(
            {
                "type": kind,
                "title": _clean(entry.get("title")) or "Diagramm",
                "unit": _clean(entry.get("unit")),
                "cite": _clean(entry.get("cite")),
                "points": points[:8],
            }
        )
    return charts[:2]


def prepare_infographic(payload: dict[str, Any]) -> tuple[bool, str]:
    items = build_items(payload)
    if len(items) < 4:
        return False, "weniger als vier Blöcke"
    payload["items"] = items
    payload["charts"] = normalize_charts(payload.get("charts"))
    return True, ""


async def create_infographic(
    session: AsyncSession, notebook: Notebook, args: dict[str, Any]
) -> dict[str, Any]:
    payload = await generate_json(
        session,
        notebook,
        topic_from_args(args, DEFAULT_TOPIC),
        SYSTEM,
        STUDIO_USER,
        source_ids_from_args(args),
        check=prepare_infographic,
    )
    title = str(payload.get("title") or "Infografik")
    return await save_artifact(session, notebook, "studio.infographic", "infographic", title, payload)
