from app.services.skills import REGISTRY, STUDIO_CATALOG
from app.services.studio.export import infographic_svg
from app.services.studio.infographic import (
    SKILL_GUIDE,
    build_items,
    items_from_citations,
    normalize_charts,
    normalize_items,
    parse_number,
)


def test_normalize_drops_repeat_titles() -> None:
    items = normalize_items(
        [
            {"label": "Testnotiz", "value": "Testnotiz", "detail": "Testnotiz"},
            {"label": "Angebot", "value": "Analysegespräch in 15 Minuten", "detail": "Kostenlos und ohne Verkaufsdruck."},
        ]
    )
    assert len(items) == 1
    assert items[0]["label"] == "Angebot"


def test_build_items_fills_from_citations() -> None:
    payload = {
        "items": [{"label": "Angebot", "value": "Analysegespräch", "detail": "15 Minuten, kostenlos."}],
        "citations": [
            {"source_title": "KI Beratung", "quote": "Vom ersten Strategiegespräch bis zur Implementierung. Messbare Ergebnisse."},
            {"source_title": "DSGVO", "quote": "Die Verordnung schützt personenbezogene Daten in der EU."},
            {"source_title": "Academy", "quote": "Die Academy bietet Zertifizierung und Schulungen für Teams."},
            {"source_title": "Studio: Quelle-Testnotiz", "quote": "# Notiz\n\nThis text was generated by AI. Check the sources."},
        ],
    }
    items = build_items(payload)
    assert len(items) >= 4
    titles = " ".join(item["value"] for item in items)
    assert "Implementierung" in titles or "Daten" in titles or "Academy" in titles


def test_items_from_citations_skips_empty() -> None:
    assert items_from_citations([{"source_title": "", "quote": "x"}]) == []


def test_infographic_svg_wraps_long_detail() -> None:
    svg = infographic_svg(
        "Grafik",
        {
            "items": [
                {
                    "label": "Prozess",
                    "value": "Ingest holt Dokumente",
                    "detail": "PDF Word HTML Markdown und Text werden in durchsuchbare Abschnitte zerlegt.",
                }
            ]
        },
    )
    assert "Ingest holt Dokumente" in svg
    assert "durchsuchbare" in svg
    assert 'width="640"' in svg


def test_parse_number_from_text() -> None:
    assert parse_number("Über 50 Integrationen") == 50
    assert parse_number(15) == 15
    assert parse_number("kein Wert") is None


def test_normalize_charts_needs_two_points() -> None:
    assert normalize_charts([{"type": "bar", "title": "X", "points": [{"label": "A", "value": 1}]}]) == []
    charts = normalize_charts(
        [{"type": "pie", "title": "Anteil", "points": [{"label": "A", "value": 20}, {"label": "B", "value": 80}]}]
    )
    assert len(charts) == 1
    assert charts[0]["type"] == "pie"


def test_normalize_charts_skips_unknown_type() -> None:
    assert (
        normalize_charts(
            [{"type": "line", "title": "X", "points": [{"label": "A", "value": 1}, {"label": "B", "value": 2}]}]
        )
        == []
    )


def test_empty_model_charts_stay_empty() -> None:
    assert normalize_charts([]) == []
    assert normalize_charts(None) == []


def test_skill_guide_documents_chart_types() -> None:
    for name in ("bar", "hbar", "pie", "number", "suffix", "caption"):
        assert name in SKILL_GUIDE
    skill = REGISTRY["studio.infographic"]
    assert skill.description_full == SKILL_GUIDE
    assert skill.card.hint == SKILL_GUIDE
    card = next(item for item in STUDIO_CATALOG if item.id == "studio.infographic")
    assert card.hint == SKILL_GUIDE


def test_normalize_keeps_number_highlight() -> None:
    items = normalize_items(
        [
            {
                "label": "Zahlen",
                "number": 70,
                "suffix": "€",
                "caption": "Zeitersparnis durch KI-Beratung",
            }
        ]
    )
    assert items[0]["number"] == "70"
    assert items[0]["suffix"] == "€"
    assert items[0]["caption"] == "Zeitersparnis durch KI-Beratung"
    assert items[0]["value"] == "Zeitersparnis durch KI-Beratung"


def test_normalize_does_not_invent_number_from_value() -> None:
    items = normalize_items(
        [{"label": "Zahlen", "value": "70 Sekunden bis 1 Stunde Zeitersparnis", "detail": "Erstgespräch kostenlos."}]
    )
    assert "number" not in items[0]


def test_infographic_svg_includes_number_highlight() -> None:
    svg = infographic_svg(
        "Grafik",
        {
            "items": [
                {
                    "label": "Zahlen",
                    "number": "70",
                    "suffix": "%",
                    "caption": "Zeitersparnis durch KI-Beratung",
                    "value": "Zeitersparnis durch KI-Beratung",
                }
            ]
        },
    )
    assert "70" in svg
    assert "%" in svg
    assert "Zeitersparnis" in svg


def test_infographic_svg_includes_bar_chart() -> None:
    svg = infographic_svg(
        "Grafik",
        {
            "items": [{"label": "Prozess", "value": "Ingest", "detail": "Holt Dateien"}],
            "charts": [
                {"type": "bar", "title": "Schichten", "points": [{"label": "Ingest", "value": 3}, {"label": "RAG", "value": 5}]}
            ],
        },
    )
    assert "Schichten" in svg
    assert "<rect" in svg
