from html import escape

import markdown
from weasyprint import HTML

AI_MARK = "This text was generated by AI. Check the sources."


def markdown_to_pdf(title: str, body: str) -> bytes:
    html_body = markdown.markdown(body, extensions=["tables", "fenced_code"])
    document = f"""<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="Everlast Notebook" />
  <meta name="X-AI-Generated" content="true" />
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: DejaVu Sans, sans-serif; font-size: 12px; line-height: 1.45; padding: 32px; }}
    h1 {{ font-size: 20px; }}
    h2 {{ font-size: 14px; margin-top: 20px; }}
    a {{ color: #1d4ed8; text-decoration: none; }}
    footer {{ margin-top: 32px; color: #555; font-size: 10px; border-top: 1px solid #ddd; padding-top: 8px; }}
  </style>
</head>
<body>
  {html_body}
  <footer>{AI_MARK}</footer>
</body>
</html>"""
    return HTML(string=document).write_pdf()
